server:
    port: 8181
    servlet:
      # 上下文路径
      context-path: /dubbo-consumer

spring:
  application:
      name: dubbo-consumer

dubbo:
  registry:
      address: nacos://192.168.0.97:8848/android-dubbo #注册地址
  application:
      name: dubbo-consumer #应用名
  consumer:
      timeout: 30000 #超时时间
